import { NgModule } from '@angular/core';
import { MatButtonModule,
         MatIconModule,
         MatInputModule ,
         MatFormFieldModule,
         MatCardModule,
         MatToolbarModule,
         MatMenuModule,
         MatDividerModule,
         MatListModule,
         MatExpansionModule,
         MatTableModule,
         MatPaginatorModule,
         MatGridListModule,
         MatSnackBarModule,
         MatTooltipModule,
         MatChipsModule,
         MatProgressBarModule
       } from '@angular/material';
@NgModule({
  imports: [
    MatButtonModule,
    MatIconModule,
    MatFormFieldModule,
    MatInputModule,
    MatCardModule,
    MatToolbarModule,
    MatMenuModule,
    MatDividerModule,
    MatListModule,
    MatExpansionModule,
    MatTableModule,
    MatPaginatorModule,
    MatGridListModule,
    MatSnackBarModule,
    MatTooltipModule,
    MatChipsModule,
    MatProgressBarModule
  ],
  exports: [
    MatButtonModule,
    MatIconModule,
    MatFormFieldModule,
    MatInputModule,
    MatCardModule,
    MatToolbarModule,
    MatMenuModule,
    MatDividerModule,
    MatListModule,
    MatExpansionModule,
    MatTableModule,
    MatPaginatorModule,
    MatGridListModule,
    MatSnackBarModule,
    MatTooltipModule,
    MatChipsModule,
    MatProgressBarModule
  ]
})
export class MaterialModule {}
